### ISSUE TITLE
Page Support Files not generated when pages are pushed via skuid-grunt

### ISSUE THREAD

**Issue by gbreavin** [skuid/skuid-grunt#1]
As per the title, in a Salesforce org with the "Generate Page Support Files" option enabled, pushing pages via skuid-grunt does not cause the Page Support files to be generated. This means that trying to view the pages in a Community built on a template will not work if Javascript snippets are included. You can push the "Generate for existing pages" button manually and the pages will start working, but it'd be nice if the setting was honoured by whatever API call skuid-grunt makes.

**Comment by zachelrath** [comment]
As of the latest Skuid releases (12.x), Page Support Files are no longer used, so we're closing this.
