### ISSUE TITLE
published package has numerous vulnerability warnings

### ISSUE THREAD

**Issue by pogilvie** [skuid/skuid-grunt#3]
+ skuid-grunt@1.1.3
added 45 packages from 99 contributors and audited 13800 packages in 8.381s
found 167 vulnerabilities (61 low, 75 moderate, 27 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by zachelrath** [comment]
Thanks for reporting this Peter.

**Comment by pogilvie** [comment]
Thanks Zach.  I no longer think this is a skuid-grunt issue.  I found that npm install ‘ing grunt-cli generated the same warnings.   A ran

pogilvie::~/Clients/hyp/project-> npm audit fix
npm WARN hyp@0.1.0 No description
npm WARN hyp@0.1.0 No repository field.
npm WARN hyp@0.1.0 No license field.

added 16 packages from 18 contributors and updated 1 package in 4.397s
fixed 10 of 60 vulnerabilities in 1327 scanned packages
  9 vulnerabilities required manual review and could not be updated
  4 package updates for 41 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or do it by hand)



Seems to have help.   Sorry for the noise.

Peter
